### ISSUE TITLE
About page: placeholder image

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-site#10]
@sashasashasasha Is there an updated image you have that we can replace with the 'placeholder image' in the mockups?

Feedback from client:
- [ ] Add a screenshot of the explorer with ‘Change in gini coefficient from 2013 to 2018’ enabled

![Screen Shot 2021-02-17 at 11.38.03 AM.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/12617b32-51ee-4699-97ed-2066f7aa3bab)

**Comment by sashasashasasha** [comment]
@laurendoone The issue with having a screenshot of the explorer here is that the explorer isn't complete yet. We can add another photo here instead.

**Comment by sashasashasasha** [comment]
<img width="702" alt="Screenshot 2021-02-23 at 18 19 59" src="https://user-images.githubusercontent.com/12460782/108889069-d6767900-7603-11eb-849e-2726150e25f1.png">

I have dropped in a collage that can replace this for now. This is in the Figma file

**Comment by laurendoone** [comment]
@sashasashasasha thank you! assigning to connor now
