### ISSUE TITLE
Remove logo from header

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-site#14]
@sashasashasasha to confirm - but from the mockups, it looks like the logo appears in the hero image and we don't need the logo in the header (as it is on staging)?

Mockups:
![Screen Shot 2021-02-17 at 12.47.36 PM.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/93377ff0-4371-4085-9b5f-a901c381f1e0)

Staging:
![image.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/5516fba1-f9a0-4c8e-b2e3-b13d46ec5c4a)

**Comment by sashasashasasha** [comment]
@laurendoone yes the logo appears in every hero section of every page. At the moment the logo has a white background. Would it be possible to remove this? 

<img width="697" alt="Screenshot 2021-02-23 at 18 04 57" src="https://user-images.githubusercontent.com/12460782/108887147-c2317c80-7601-11eb-8437-b08e39a7b5c1.png">

**Comment by laurendoone** [comment]
@sashasashasasha yes tracking in a new issue https://github.com/Hyperobjekt/untd-map/issues/40
