### ISSUE TITLE
The Research Library page + 3 topic tabs

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/untd-site#2]
- [ ] Basic layout and styling for library page
- [ ] 3 or so "tabs" of accordion content filled in
- [ ] Tabs need to be able to load body text (markdown) with images in the body text (probably should implement using a separate directory for this feature, with an mdx file for each tab), as well as a frontmatter list of "resources" which are links to research articles
- [ ] Other tabs can say "coming soon"

**Comment by laurendoone** [comment]
@touchRED some additional info:

- Copy is here (starts on page 7): https://docs.google.com/document/d/1DdEfUUQ5ZsNBSvejBzCwBdyWUcHFmucwkEAjQ9ytSYE/edit#heading=h.te82lju4jjye
- It looks like the copy deck has a few more topics than are shown in the mockup - will confirm with Sasha whether to follow copy deck or the mockup (my assumption is to follow the copy deck)
- We are confirming with the client whether we need to add the descriptions of each topic (as seen in the copy deck)
- We only need to populate **2** topics with real content for the Feb 26 demo: Socioeconomic Mobility and (? TBD, to confirm with client on 2/18). For all other topics, just say "coming soon"
- At the bottom of each topic, there is a Resources section. Find the relevant links here: https://github.com/childpovertyactionlab/Social-Mobility/blob/testing/SocialMobility_Literature_Links.csv. The copy deck also references which section/category to pull the links from

**Comment by laurendoone** [comment]
@touchRED some more updates from our client meeting:

- Use the copy deck (starts on page 7) https://docs.google.com/document/d/1DdEfUUQ5ZsNBSvejBzCwBdyWUcHFmucwkEAjQ9ytSYE/edit#heading=h.te82lju4jjye for the updated, full list of topics (the mockup is no longer accurate and they have added more topics)
- In the topics navigation, do NOT show the descriptions next to the bullet points - those are just for the main body content 
- The 3 topics to populate for the Feb 26 demo: **Socioeconomic Mobility, Family, Education**
- The copy deck has the static list of resources for each topic (no need to look at the csv in github for the demo)
