### ISSUE TITLE
Homepage: add screenshot of Explorer map to the Explorer card

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-site#26]
Feedback from client: replace the image in Explorer card on homepage with a screenshot of the Explorer
![image.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/67a148d5-4a6f-428b-a3b6-1785eef14f21)

**Comment by sashasashasasha** [comment]
@laurendoone The screenshot doesn't look great. James confirmed we can change the background for this card instead to an image with a map. I have updated the homepage mockup in Figma and added a mobile mockup above it. Page 'Latest mockups'

**Comment by laurendoone** [comment]
got it, thanks! updated in staging

**Comment by laurendoone** [comment]
@touchRED please update the CMS so the new image appears as the card background
