### ISSUE TITLE
Menu: align hovered text to unhovered text

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-site#32]
Feedback from James: Transition to italics on hover is cool; it jumps upward slightly relative to the unhovered text though. Would be great to have the 2 states vertically aligned.

![image](https://user-images.githubusercontent.com/76966798/109207288-d094ab00-775d-11eb-85c5-52c490b5a575.png)

**Comment by touchRED** [comment]
@laurendoone this fix got pushed up before the ticket got made – this is good to go ✅

**Comment by laurendoone** [comment]
awesome thanks! closing this ticket then
