### ISSUE TITLE
Homepage: add a slide out interaction on hover to 'Source' below chart

### ISSUE THREAD

**Issue by sashasashasasha** [Hyperobjekt/untd-site#37]
On hover the light background could slide out and reveal the source for the chart. If this is difficult to implement then the text (Chetty et al. "The Fading American Dream: Trends in Absolute Income Mobility Since 1940.") can just go here on its own with no hover interaction, background, icon or 'Source' text. 

This is in [Figma.](https://www.figma.com/file/Xxu6JB55X7j77cGahUmqWO/UNTD-Mockups-and-Wireframes?node-id=566%3A0)

**Comment by laurendoone** [comment]
@sashasashasasha can you check staging and see if that slide out interaction is as expected? https://staging--socialmobility.netlify.app/
